// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHTML(arg1) {
  return window['go']['main']['App']['ExportHTML'](arg1);
}

export function ExportJSON(arg1) {
  return window['go']['main']['App']['ExportJSON'](arg1);
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
