// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ExportHTML(arg1:model.Report):Promise<string>;

export function ExportJSON(arg1:model.Report):Promise<string>;

export function LogFrontendError(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Scan(arg1:model.ScanOptions):Promise<model.Report>;

export function Version():Promise<Record<string, string>>;
